### ISSUE TITLE
Syntax Error on line 142

### ISSUE THREAD

**Issue by oblivion2k** [woodenphone/Derpibooru-dl#21]
Derpibooru-dl-derpibooru_dl-2016-7-1>python derpibooru_dl.py
  File "derpibooru_dl.py", line 142
    except urllib2.HTTPError, err:
                            ^
SyntaxError: invalid syntax

Looks like git isn't formatting the code correctly. Carot appears underneath the comma after HTTPError.

**Comment by mkody** [comment]
To make a block of code, use 3 " ` " at the start and the end of your code. [See here.](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code)

You're using Python 3. This project requires Python 2.
[![zx5h1](https://cloud.githubusercontent.com/assets/843787/16544981/51c72c8e-4112-11e6-9b29-ed12eac35c75.png)](https://cloud.githubusercontent.com/assets/843787/16544981/51c72c8e-4112-11e6-9b29-ed12eac35c75.png)

**Comment by oblivion2k** [comment]
Got it working with Python 2. Interestingly, it wasn't importing derpibooru correctly, until I removed that line from the code. Then it make the prerequisite folders and configuration files, and gave an error once I tried to download something. I then added the derpibooru import back in, and it's ran fine ever since. Maybe just an issue on my end. Anyway, closing issue.
