### ISSUE TITLE
Best downloader is not working again.

### ISSUE THREAD

**Issue by mornhold** [woodenphone/Derpibooru-dl#38]
Please give me a help to this problem. 

2020-04-02 10:05:03,951 - DEBUG - Logging started.
2020-04-02 10:05:04,680 - DEBUG - <httperror_seek_wrapper (urllib2.HTTPError ins
tance) at 0x2e19dc0 whose wrapped object = <closeable_response at 0x2e278a0 whos
e fp = <response_seek_wrapper at 0x2e3d238 whose wrapped object = <closeable_res
ponse at 0x2e3d530 whose fp = <socket._fileobject object at 0x02E1FF30>>>>>

Once again I apologize and hope for help.

**Comment by liamwhite** [comment]
Use a different downloader like <https://github.com/Sibusten/derpibooru-downloader>. This one is no longer maintained.
